server:
  port: 8080

spring:

  mvc:
    servlet:
      path: /api

  datasource:
    url: jdbc:h2:mem:blog;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/realm-sangkhim
        jwt.jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  rabbitmq:
    dynamic: true
    host: localhost
    port: 15672
    username: guest
    password: guest

jwt:
  auth:
    converter.resource-id: client-sangkhim
    converter.principal-attribute: preferred_username

keycloak:
  realm: realm-sangkhim
  auth-server-url: http://localhost:18080/realms/${keycloak.realm}/protocol/openid-connect/token

springdoc:
  swagger-ui:
    oauth:
      client-id: client-sangkhim
      client-secret: 41OSOFH2IpsA29IEhDvbBIssWFbSsjP8
      realm: realm-sangkhim

management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    startup:
      enabled: true